### ISSUE TITLE
Unable to run a self hosted bot

### ISSUE THREAD

**Issue by KingColton1** [tybug/snitchvisbot#6]
Followed through your install instructions. But as soon as I run python main.py (python3 main.py in my case), I got this error;
`Traceback (most recent call last):
  File "/root/snitchvisbot/main.py", line 18, in <module>
    from snitchvis import (Event, InvalidEventException, SnitchVisRecord,
  File "/usr/local/lib/python3.10/dist-packages/snitchvis/__init__.py", line 1, in <module>
    from snitchvis.visualizer import (Snitchvis, SnitchvisApp, parse_events,
  File "/usr/local/lib/python3.10/dist-packages/snitchvis/visualizer.py", line 8, in <module>
    from PyQt6.QtGui import QPalette, QColor, QShortcut, QImage
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory`

I looked at the various of the codes as well as snitchvis repo and they all pointed to the missing dependencies that apparently not installed or readable? Here's what install progress looked like;

`<name>@<server name>:~/snitchvisbot# pip install -r requirements.txt
Collecting snitchvis
  Cloning https://github.com/tybug/snitchvis to /tmp/pip-install-iatlklmn/snitchvis_29ebe003af7b47e590cfccb329b5988a
  Running command git clone --filter=blob:none --quiet https://github.com/tybug/snitchvis /tmp/pip-install-iatlklmn/snitchvis_29ebe003af7b47e590cfccb329b5988a
  Resolved https://github.com/tybug/snitchvis to commit e105974f704faea1469ab8ce2e9fe26fae32a8c7
  Preparing metadata (setup.py) ... done
Collecting discord.py
  Downloading discord.py-2.4.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 23.1 MB/s eta 0:00:00
Collecting dateparser~=1.1
  Downloading dateparser-1.2.0-py2.py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 KB 55.3 MB/s eta 0:00:00
Collecting PyQt6
  Downloading PyQt6-6.7.1-1-cp38-abi3-manylinux_2_28_x86_64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 51.2 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 60.1 MB/s eta 0:00:00
Collecting aiohttp<4,>=3.7.4
  Downloading aiohttp-3.10.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 94.6 MB/s eta 0:00:00
Collecting tzlocal
  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Collecting regex!=2019.02.19,!=2021.8.27
  Downloading regex-2024.9.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (782 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.7/782.7 KB 65.8 MB/s eta 0:00:00
Collecting python-dateutil
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 7.4 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from dateparser~=1.1->-r requirements.txt (line 3)) (2022.1)
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting aiohappyeyeballs>=2.3.0
  Downloading aiohappyeyeballs-2.4.3-py3-none-any.whl (14 kB)
Collecting yarl<2.0,>=1.12.0
  Downloading yarl-1.15.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (314 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.5/314.5 KB 66.9 MB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 2)) (21.2.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 KB 49.9 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 KB 28.8 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting PyQt6-sip<14,>=13.8
  Downloading PyQt6_sip-13.8.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (284 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.6/284.6 KB 41.2 MB/s eta 0:00:00
Collecting PyQt6-Qt6<6.8.0,>=6.7.0
  Downloading PyQt6_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl (74.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 MB 20.2 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->dateparser~=1.1->-r requirements.txt (line 3)) (1.16.0)
Collecting typing-extensions>=4.1.0
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting propcache>=0.2.0
  Downloading propcache-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (208 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.9/208.9 KB 54.9 MB/s eta 0:00:00
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.12.0->aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 2)) (3.3)
Building wheels for collected packages: snitchvis
  Building wheel for snitchvis (setup.py) ... done
  Created wheel for snitchvis: filename=snitchvis-1.0.3-py3-none-any.whl size=188951135 <sha256 code>
  Stored in directory: <path to a wheel cache>
Successfully built snitchvis
Installing collected packages: PyQt6-Qt6, tzlocal, typing-extensions, regex, python-dateutil, PyQt6-sip, propcache, numpy, frozenlist, async-timeout, aiohappyeyeballs, PyQt6, multidict, dateparser, aiosignal, yarl, snitchvis, aiohttp, discord.py
Successfully installed PyQt6-6.7.1 PyQt6-Qt6-6.7.3 PyQt6-sip-13.8.0 aiohappyeyeballs-2.4.3 aiohttp-3.10.10 aiosignal-1.3.1 async-timeout-4.0.3 dateparser-1.2.0 discord.py-2.4.0 frozenlist-1.4.1 multidict-6.1.0 numpy-2.1.2 propcache-0.2.0 python-dateutil-2.9.0.post0 regex-2024.9.11 snitchvis-1.0.3 typing-extensions-4.12.2 tzlocal-5.2 yarl-1.15.5`

Successful installation, but can't run for some reason. I tried run them in pterodactyl, a server panel where I often use them to host all of my Discord bots. Even when I fire up a empty virtual machine in my Proxmox server and in digitalocean, all show me same error result. I think there is a problem in your installation script but honestly I don't know any solution.

edited: I got your discord username, sent a DM.

**Comment by Liam-DeVoe** [comment]
This is very likely to be some qt runtime dependency missing based on `libEGL.so.1: cannot open shared object file: No such file or directory`. This is probably a quirk of whatever specific linux distribution you're using.

I don't really have the bandwidth to debug individual setups or machines, sorry. I would recommend looking into what `libEGL` is and if you can install it separately.
